language: julia
codecov: true

## Documentation: http://docs.travis-ci.com/user/languages/julia/

os:
  - linux
  - osx
julia:
  - 1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
jobs:
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip